language: java
dist: trusty
sudo: false
install: true

addons:
  sonarcloud:
    organization: "stylianos-agapiou-sonarsource-gi"
    token:
      secure: "URb1Amb3YQaxuQAYoSfL0uhjtn9iZZwaR4JiYIzP1CKi5MXGDv8OuNQKF0uXLOBWQztBrV9bRKHmqGd2tbMVDajTH2F3t9HUDtLSW6P+iVAVnzpCd7CUXeKXF0KPtOGWnucYr7z6hHFOX31U4lBg4x9gS1AqT78E8eFT2p7GhwY3HY8IejjUcASHfyqaggycuaMFFsfvROJmnjuusF2akgCEMEoXLcARjF9Zur8/UN74VOYQrcbFaWHY6UHWpUEoZL8hNL1EvuMBuK/wwzGfrkIw46ICyu4+FR8Cc8tGcpRCUAVPxyQY13vELDkeqfAvgLi44veQK73JpVg41evbIWwhlYCVLwtSlvTcHNbeKY0GI2vWIEWPW/MttK51tflb/3ILW7o0Hiu8SIkhrD022uaNbASpCpG/0hoK21uqenGb0zla8+15o+UZjUQ0lvDRo4MVs+VD1r/Hi0gOLlE2ruAtK/uCpjAUqLlzqdkjbPPivBs74izrCxwUquYBYVrZ02ZS8P5RehCtvYjInkNx6LVZgURPZXBEDbDZWt2cKQtwlegvn+PON8Q1RBRL4RuFXhjo/UGmbNeBYrW5MJQke7zBHAXCWvljXxA+uOrenHt84027Al+3+1fVizFVo8fxIjocWnleJv58cJDpPTbnH8N9sgWDf2fj+dcUr8j1XZY="
jdk:
  - oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
