language: java
sudo: false
install: true

jdk: oraclejdk8

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.organization=stylianos-agapiou-sonarsource-gi -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=0167de3381c10e9ba3b6a7c05940809bf6c2fdb4

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
